version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ssm-user/action
    overwrite: yes

permissions:
  - object: /home/ssm-user/action
    pattern: "**"
    owner: ssm-user
    group: ssm-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
