running: dev
domain: http://3.35.252.234:8080

awsParameterStorePropertySource:
  enabled: true

spring:
  profiles:
    include: common
    active: dev
  datasource:
    url: ${/spring-boot-aws/main014/spring.datasource.url}
    username: ${/spring-boot-aws/main014/spring.datasource.username}
    password: ${/spring-boot-aws/main014/spring.mail.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${/spring-boot-aws/main014/spring.security.oauth2.client.registration.kakao.client-id}
            redirect-uri: "http://3.35.252.234:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${/spring-boot-aws/main014/spring.mail.username}
    password: ${/spring-boot-aws/main014/spring.mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
jwt:
  secret: ${/spring-boot-aws/main014/jwt.secret}
  access-token-expiration-minutes: 1800000
  refresh-token-expiration-minutes: 604800000
cloud:
  aws:
    credentials:
      accessKey: ${/spring-boot-aws/main014/cloud.aws.credentials.access-key}
      secretKey: ${/spring-boot-aws/main014/cloud.aws.credentials.secret-key}
    s3:
      bucket: main014-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
mail:
  address:
    admin: admin@gmail.com
